import { CircleCheck, Lightbulb, ListChecks, Sparkles } from 'lucide-react'
import type { Summary } from '../../types'
import { Badge, EmptyState, SectionLabel } from '../ui'

export function SummaryPanel({ summary }: { summary: Summary | null }) {
  if (!summary) {
    return (
      <EmptyState
        icon={<Sparkles size={22} />}
        title="No summary yet"
        description="This meeting has not been processed."
      />
    )
  }

  return (
    <div className="max-w-3xl space-y-7 p-5 lg:p-6">
      <section>
        <SectionLabel icon={<Sparkles size={13} />} className="mb-3">
          Overview
        </SectionLabel>
        <p className="text-[15px] leading-[1.7] text-ink">{summary.overview}</p>
        <div className="mt-3.5 flex flex-wrap gap-1.5">
          {summary.topics.map((topic) => (
            <Badge key={topic} tone="accent">
              {topic}
            </Badge>
          ))}
        </div>
      </section>

      {summary.key_points.length > 0 && (
        <section>
          <SectionLabel icon={<ListChecks size={13} />} className="mb-3">
            Key points
          </SectionLabel>
          <ul className="space-y-2.5">
            {summary.key_points.map((point) => (
              <li key={point} className="flex gap-3 text-sm leading-[1.65] text-ink-soft">
                <span className="mt-[9px] size-1 shrink-0 rounded-full bg-ink-faint" />
                {point}
              </li>
            ))}
          </ul>
        </section>
      )}

      {summary.decisions.length > 0 && (
        <section>
          <SectionLabel icon={<CircleCheck size={13} />} className="mb-3">
            Decisions
          </SectionLabel>
          <ul className="space-y-2">
            {summary.decisions.map((decision) => (
              <li
                key={decision}
                className="flex gap-2.5 rounded-lg border border-line bg-canvas px-3.5 py-3 text-sm leading-[1.6] text-ink-soft"
              >
                <CircleCheck size={15} className="mt-0.5 shrink-0 text-positive" />
                {decision}
              </li>
            ))}
          </ul>
        </section>
      )}

      {summary.insights.length > 0 && (
        <section>
          <SectionLabel icon={<Lightbulb size={13} />} className="mb-3">
            AI insights
          </SectionLabel>
          <ul className="space-y-3">
            {summary.insights.map((insight) => (
              <li
                key={insight}
                className="border-l-2 border-accent/35 pl-3.5 text-sm leading-[1.65] text-ink-soft"
              >
                {insight}
              </li>
            ))}
          </ul>
        </section>
      )}

      <p className="border-t border-line pt-3.5 text-xs text-ink-faint">
        {summary.generated_by === 'llm'
          ? 'Generated by the configured language model.'
          : 'Generated without an LLM key, using the built-in fallback summariser.'}
      </p>
    </div>
  )
}
