import { useQuery } from '@tanstack/react-query'
import { CircleCheck, Lightbulb, ListChecks, Play, Sparkles } from 'lucide-react'
import type { SummaryItem } from '../../types'
import { api } from '../../lib/api'
import { timecode } from '../../lib/format'
import { EmptyState, ErrorState, Skeleton, cx } from '../ui'

/** Says where the summary came from, without overstating any of the three. */
const PROVENANCE: Record<string, string> = {
  llm: 'Generated by the configured language model from this transcript.',
  local: 'Extracted from the transcript on the server. Add an API key in Settings for an AI-written summary.',
  authored: 'Written by hand as part of this demo meeting. Record a meeting to see a generated summary.',
  none: 'No summary could be produced for this template.',
}

const SECTION_ICON: Record<string, React.ReactNode> = {
  'Key points': <ListChecks size={12} />,
  Decisions: <CircleCheck size={12} />,
  'AI insights': <Lightbulb size={12} />,
}

export function SummaryPanel({
  meetingId,
  template,
  onTemplateChange,
  onPlay,
}: {
  meetingId: number
  template: string
  onTemplateChange: (template: string) => void
  onPlay: (time: number) => void
}) {
  const templates = useQuery({ queryKey: ['templates'], queryFn: api.templates })

  const { data, isPending, error, refetch } = useQuery({
    queryKey: ['summary', meetingId, template],
    queryFn: () => api.summary(meetingId, template),
  })

  const active = templates.data?.find((option) => option.id === template)

  return (
    <div>
      {/* The template is a control, not content, so it sits in its own strip
          above the summary instead of floating over the first paragraph. */}
      <div className="flex flex-wrap items-center gap-x-3 gap-y-1.5 border-b border-line bg-raised/40 px-5 py-2.5 lg:px-6">
        <label
          htmlFor="summary-template"
          className="text-[10px] font-semibold tracking-[0.12em] text-ink-faint uppercase"
        >
          Template
        </label>
        <select
          id="summary-template"
          value={template}
          onChange={(event) => onTemplateChange(event.target.value)}
          className="h-7 border border-line bg-surface px-2 text-[13px] font-medium text-ink outline-none focus:border-accent"
        >
          {(templates.data ?? []).map((option) => (
            <option key={option.id} value={option.id}>
              {option.label}
            </option>
          ))}
        </select>
        {active && <span className="text-xs text-ink-faint">{active.description}</span>}
      </div>

      <div className="max-w-3xl p-5 lg:p-6">
        {isPending && (
          <div className="space-y-3">
            <Skeleton className="h-4 w-full" />
            <Skeleton className="h-4 w-11/12" />
            <Skeleton className="h-24 w-full" />
          </div>
        )}

        {error && <ErrorState message={(error as Error).message} onRetry={refetch} />}

        {data && (
          <div className="space-y-8">
            <section>
              <Heading icon={<Sparkles size={12} />}>Overview</Heading>
              {/* The overview is the one paragraph everybody reads, so it gets
                  the accent rule and a size of its own. */}
              <p className="border-l-2 border-accent pl-4 text-[15.5px] leading-[1.7] text-ink">
                {data.overview}
              </p>
              {data.topics.length > 0 && (
                <div className="mt-4 flex flex-wrap gap-x-4 gap-y-1.5 pl-4">
                  {data.topics.map((topic) => (
                    <span
                      key={topic}
                      className="text-[11px] font-medium tracking-[0.04em] text-ink-faint uppercase"
                    >
                      {topic}
                    </span>
                  ))}
                </div>
              )}
            </section>

            {data.sections.map((section) => (
              <section key={section.label}>
                <Heading icon={SECTION_ICON[section.label] ?? <ListChecks size={12} />}>
                  {section.label}
                </Heading>
                <ul className={cx(section.items.some(playable) && 'border-t border-line')}>
                  {section.items.map((item) => (
                    <Item
                      key={item.text}
                      item={item}
                      timed={section.items.some(playable)}
                      onPlay={onPlay}
                    />
                  ))}
                </ul>
              </section>
            ))}

            {data.sections.length === 0 && (
              <EmptyState
                title="Nothing for this template"
                description="This meeting does not cover the sections this template looks for. Try another one."
              />
            )}

            <p className="border-t border-line pt-3.5 text-xs text-ink-faint">
              {PROVENANCE[data.generated_by] ?? PROVENANCE.local}
            </p>
          </div>
        )}
      </div>
    </div>
  )
}

const playable = (item: SummaryItem) => item.timestamp !== null

function Heading({ icon, children }: { icon: React.ReactNode; children: React.ReactNode }) {
  return (
    <div className="mb-3 flex items-center gap-2.5">
      <h3 className="flex items-center gap-1.5 text-[10px] font-semibold tracking-[0.12em] text-ink-faint uppercase">
        {icon}
        {children}
      </h3>
      <span className="h-px flex-1 bg-line" />
    </div>
  )
}

/**
 * A section either cites the transcript or it does not.
 *
 * Where it does, every row keeps a timecode column so the citations line up and
 * the ones without a quote are visibly the ones you cannot jump to. Where none
 * of them do, the column would be a row of blanks, so the list stays a plain
 * bulleted one.
 */
function Item({
  item,
  timed,
  onPlay,
}: {
  item: SummaryItem
  timed: boolean
  onPlay: (time: number) => void
}) {
  if (!timed) {
    return (
      <li className="flex gap-3 py-1.5 text-sm leading-[1.65] text-ink-soft">
        <span className="mt-[9px] size-1 shrink-0 rounded-full bg-ink-faint" />
        {item.text}
      </li>
    )
  }

  if (item.timestamp === null) {
    return (
      <li className="flex gap-4 border-b border-line py-2.5">
        <span className="w-14 shrink-0 font-mono text-[11px] text-ink-faint">&mdash;</span>
        <span className="text-sm leading-[1.6] text-ink-soft">{item.text}</span>
      </li>
    )
  }

  return (
    <li>
      <button
        onClick={() => onPlay(item.timestamp!)}
        className="group flex w-full gap-4 border-b border-line py-2.5 text-left transition-colors hover:bg-raised/50"
      >
        <span className="flex w-14 shrink-0 items-center gap-1 font-mono text-[11px] text-ink-faint transition-colors group-hover:text-accent">
          <Play size={10} className="opacity-0 transition-opacity group-hover:opacity-100" />
          {timecode(item.timestamp)}
        </span>
        <span className="text-sm leading-[1.6] text-ink-soft">{item.text}</span>
      </button>
    </li>
  )
}
